select=["E", "F", "I", "W", "N", "UP", "ANN", "RUF"]
ignore=["ANN101", "ANN001", "ANN002", "ANN003", "RUF012"]
exclude=["tests/*.py", "examples/*.py", "malevich/square/*.py"]

[per-file-ignores]
"__init__.py" = ["E402", "F", "I"]

