name: Malevich Manual CI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'On which branch to run'
        required: true
jobs:
  build_push:
    environment: ${{{{ inputs.branch }}}}
    runs-on: ubuntu-latest
    if: ${{{{ github.ref_type == 'branch' }}}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{{{ inputs.branch }}}}
      - name: "Environment name"
        run: echo "Runs in ${{{{ vars.ENV_NAME }}}}"
      - name: Malevich CI Actions
        uses: MalevichAI/auto-ci@v0.2.0
        with:
          registry: ${{{{ secrets.REGISTRY_TYPE }}}}
          registry_url: ${{{{ secrets.REGISTRY_URL }}}}
          registry_id: ${{{{ secrets.REGISTRY_ID }}}}
          username: ${{{{ secrets.IMAGE_USERNAME }}}}
          password: ${{{{ secrets.IMAGE_PASSWORD }}}}
          space_username: ${{{{ secrets.SPACE_USERNAME }}}}
          space_password: ${{{{ secrets.SPACE_PASSWORD }}}}
          api_url: ${{{{ secrets.API_URL }}}}
          org_id: ${{{{ secrets.SPACE_ORGANIZATION_ID }}}}