"""
THIS FILE IS AUTOGENERATED BY malevich PACKAGE INSTALLER.

THIS FILE CONTAINS VITAL INFORMATION ABOUT THE PACKAGE AND ITS CONTENTS.
DO NOT MODIFY THIS FILE MANUALLY.
"""

from malevich._autoflow.function import autotrace
from malevich._utility.registry import Registry
from malevich.models.nodes import OperationNode

from pydantic import BaseModel

class default_scheme(BaseModel):
	pass

Registry().register("e23a6f0f19f482ec52de26ce985994b406016ca6d27d9e694cf00b561d9a471e", {
    "image_ref": ('dependencies', 'testapp', 'options', 'image_ref'),
    "image_auth_user": ('dependencies', 'testapp', 'options', 'image_auth_user'),
    "image_auth_pass": ('dependencies', 'testapp', 'options', 'image_auth_pass'),
    "processor_id": "two_outputs",
})

@autotrace
def two_outputs(config: dict = {}):
    """None"""
    return OperationNode(operation_id="e23a6f0f19f482ec52de26ce985994b406016ca6d27d9e694cf00b561d9a471e", config=config)

Registry().register("b3c3c51efed29519a187bf8ffdfd05e65f0cd82ab6a6ebd3251a7fb0f7984bef", {
    "image_ref": ('dependencies', 'testapp', 'options', 'image_ref'),
    "image_auth_user": ('dependencies', 'testapp', 'options', 'image_auth_user'),
    "image_auth_pass": ('dependencies', 'testapp', 'options', 'image_auth_pass'),
    "processor_id": "share_file_and_folder",
})

@autotrace
def share_file_and_folder(config: dict = {}):
    """None"""
    return OperationNode(operation_id="b3c3c51efed29519a187bf8ffdfd05e65f0cd82ab6a6ebd3251a7fb0f7984bef", config=config)

__checksum = 'de3e8093aa02151d558897e2046fd98599c6138dc256f7bf4c136bdf6767715d'
