# generated by datamodel-codegen:
#   filename:  tmp4ougxsxr.json
#   timestamp: 2024-07-16T08:40:55+00:00




from typing import Any

from malevich.models._model import _Model
from pydantic import Field


class DefaultScheme(_Model):
    data: Any = Field(..., title='Data')

# generated by datamodel-codegen:
#   filename:  tmpwoytk28j.json
#   timestamp: 2024-07-16T08:40:55+00:00




from malevich.models._model import _Model
from pydantic import Field


class Obj(_Model):
    path: str = Field(..., title='Path')

# generated by datamodel-codegen:
#   filename:  tmp4hql8k59.json
#   timestamp: 2024-07-16T08:40:55+00:00




from datetime import datetime
from typing import List, Optional

from malevich.models._model import _Model
from pydantic import Field


class Metadata(_Model):
    created_at: Optional[datetime] = Field(None, title='Created At')
    edited_at: Optional[datetime] = Field(None, title='Edited At')


class SimpleRequest(_Model):
    title: str = Field(..., title='Title')
    description: str = Field(..., title='Description')
    images: Optional[List[str]] = Field(None, title='Images')
    metadata: Metadata

# generated by datamodel-codegen:
#   filename:  tmpflxvybk1.json
#   timestamp: 2024-07-16T08:40:55+00:00




from datetime import datetime
from typing import List, Optional

from malevich.models._model import _Model
from pydantic import Field


class SimpleResponse(_Model):
    metadata: Metadata
    vector: List[float] = Field(..., title='Vector')

