name: Pytest
on:
  push:
    branches:
      - test
jobs:
  build:
    if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/test' }}
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        run: |
          echo ${{ secrets.TEST_GHCR_PACKAGE_PASSWORD }} | docker login --username USERNAME --password-stdin ghcr.io
      - name: Docker build/push
        run: |
          cd ./tests/apps
          for path in */
          do
            if [[ -f $path/Dockerfile ]];
            then
              name="$(basename $path)"
              tag="ghcr.io/malevichai/test:$name"
              echo "Building $name from $path"
              docker build $path -q -t $tag
              docker push $tag
            fi
          done
  pytest:
    if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/test' }}
    needs: build
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: "malevich"

    - name: Install Python
      uses: actions/setup-python@v4
      with:
         python-version: '3.11'

    - name: Install Malevich
      run: |
        pip install -r ./malevich/requirements.dev.txt
        pip install ./malevich
        malevich init
        malevich space login --username=${{secrets.TESTS_SPACE_USER}} --password=${{secrets.TESTS_SPACE_PASSWORD}} --api-url=${{secrets.TESTS_API_URL}} --no-input
        mkdir -p ~/.malevich/testing
        cp malevich.yaml ~/.malevich/testing
        cp malevich.secrets.yaml ~/.malevich/testing


    - name: Test build app
      run: |
        docker build -t ghcr.io/malevichai/simple_app:latest tests/app_build/simple_app
        docker push ghcr.io/malevichai/simple_app:latest
        malevich use image simple_app ramprin/simple_app:latest USERNAME ${{ secrets.TEST_GHCR_PACKAGE_PASSWORD }}
        pytest -rP tests/app_build/