name: Pytest
on:
  push:
    branches:
      - test
    paths-ignore:
      - .github/**
      - malevich/tests/**
  workflow_dispatch:
jobs:
  build:
    if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/test' }}
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        run: |
          echo ${{ secrets.TEST_GHCR_PACKAGE_PASSWORD }} | docker login --username malevichai --password-stdin ghcr.io
      - name: Docker build/push
        run: |
          cd ./tests/apps
          for path in */
          do
            if [[ -f $path/Dockerfile ]];
            then
              name="$(basename $path)"
              tag="ghcr.io/malevichai/test:$name"
              echo "Building $name from $path"
              docker build $path -q -t $tag
              docker push $tag
            fi
          done
          cd ../non_suite/
          docker build -q -t ghcr.io/malevichai/test:simple_app simple_app/
          docker push -q ghcr.io/malevichai/test:simple_app
  pytest:
    if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/test' }}
    needs: build
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: "malevich"

    - name: Install Python
      uses: actions/setup-python@v4
      with:
         python-version: '3.11'

    - name: Install Malevich
      run: |
        pip install -r ./malevich/requirements.dev.txt
        pip install ./malevich
        malevich init
        malevich space login --username=${{secrets.TESTS_SPACE_USER}} --password=${{secrets.TESTS_SPACE_PASSWORD}} --api-url=${{secrets.TESTS_API_URL}} --no-input
        mkdir -p ~/.malevich/testing
        cp malevich.yaml ~/.malevich/testing
        cp malevich.secrets.yaml ~/.malevich/testing

    - name: Testing
      run: |
        cp -rf ./malevich/tests ./tests && rm -rf ./malevich
        pytest -s tests/suite/
      env:
        TESTS_SPACE_PASSWORD: ${{ secrets.TESTS_SPACE_PASSWORD }}
        TESTS_SPACE_USER: ${{ secrets.TESTS_SPACE_USER }}
        TEST_GHCR_PACKAGE_PASSWORD: ${{ secrets.TEST_GHCR_PACKAGE_PASSWORD }}
        MALEVICH_TEST_DIR: ${{ secrets.MALEVICH_TEST_DIR }}
        CORE_USER: ${{ secrets.CORE_USER }}
        CORE_PASS: ${{ secrets.CORE_PASS }}

    - name: Test build app, endpoints and platforms
      run: |
        malevich use image simple_app ghcr.io/malevichai/test:simple_app malevichai ${{ secrets.TEST_GHCR_PACKAGE_PASSWORD }}
        malevich install utility
        pytest -rP tests/non_suite/
      env:
        CORE_USER: ${{ secrets.CORE_USER }}
        CORE_PASS: ${{ secrets.CORE_PASS }}

    - name: Clear core tasks
      if: always()
      run: |
        echo "Not Implemented Yet. Waiting for core test account."
        python .github/workflows/clean.py
      env:
        CORE_USER: ${{ secrets.CORE_USER }}
        CORE_PASS: ${{ secrets.CORE_PASS }}
